export const GAME_IMAGE_MANIFEST: Record<
  string,
  { logoFile: string; characters: { name: string; file: string }[] }
> = {
  sf6: {
    logoFile: "sf6logo.png",
    characters: [
      { name: "Ryu", file: "ryu.png" },
      { name: "Luke", file: "luke.png" },
      { name: "Jamie", file: "jamie.png" },
      { name: "Chun-Li", file: "chunli.png" },
      { name: "Guile", file: "guile.png" },
      { name: "Kimberly", file: "kimberly.png" },
      { name: "Juri", file: "juri.png" },
      { name: "Ken", file: "ken.png" },
      { name: "Blanka", file: "blanka.png" },
      { name: "Dhalsim", file: "dhalsim.png" },
      { name: "E. Honda", file: "ehonda.png" },
      { name: "Dee Jay", file: "deejay.png" },
      { name: "Manon", file: "manon.png" },
      { name: "Marisa", file: "marisa.png" },
      { name: "JP", file: "jp.png" },
      { name: "Zangief", file: "zangief.png" },
      { name: "Lily", file: "lily.png" },
      { name: "Cammy", file: "cammy.png" },
      { name: "Rashid", file: "rashid.png" },
      { name: "A.K.I.", file: "aki.png" },
      { name: "Ed", file: "ed.png" },
      { name: "Akuma", file: "akuma.png" },
      { name: "M. Bison", file: "mbison.png" },
      { name: "Terry", file: "terry.png" },
      { name: "Mai", file: "mai.png" },
      { name: "Elena", file: "elena.png" },
      { name: "Sagat", file: "sagat.png" },
      { name: "C. Viper", file: "cviper.png" },
      { name: "Alex", file: "alex.png" },
      { name: "Ingrid", file: "ingrid.png" },
    ],
  },
  ggst: {
    logoFile: "ggstlogo.png",
    characters: [
      { name: "Sol", file: "sol.png" },
      { name: "Ky", file: "ky.png" },
      { name: "May", file: "may.png" },
      { name: "Axl", file: "axl.png" },
      { name: "Chipp", file: "chipp.png" },
      { name: "Potemkin", file: "pot.png" },
      { name: "Faust", file: "faust.png" },
      { name: "Millia", file: "millia.png" },
      { name: "Zato-1", file: "zato.png" },
      { name: "Ramlethal", file: "ram.png" },
      { name: "Leo", file: "leo.png" },
      { name: "Nagoriyuki", file: "nago.png" },
      { name: "Giovanna", file: "gio.png" },
      { name: "Anji", file: "anji.png" },
      { name: "I-No", file: "ino.png" },
      { name: "Goldlewis", file: "gold.png" },
      { name: "Jack-O'", file: "jacko.png" },
      { name: "Happy Chaos", file: "hc.png" },
      { name: "Baiken", file: "baiken.png" },
      { name: "Testament", file: "test.png" },
      { name: "Bridget", file: "brisket.png" },
      { name: "Sin", file: "sin.png" },
      { name: "Bedman?", file: "bed.png" },
      { name: "Asuka R#", file: "asuka.png" },
      { name: "Johnny", file: "johnny.png" },
      { name: "Elphelt", file: "elphelt.png" },
      { name: "A.B.A", file: "aba.png" },
      { name: "Slayer", file: "slayer.png" },
      { name: "Dizzy", file: "dizzy.png" },
    ],
  },
  xko: {
    logoFile: "2xkologo.png",
    characters: [
      { name: "Ahri", file: "ahri.png" },
      { name: "Akali", file: "akali.png" },
      { name: "Blitzcrank", file: "blitzcrank.png" },
      { name: "Braum", file: "braum.png" },
      { name: "Caitlyn", file: "caitlyn.png" },
      { name: "Darius", file: "darius.png" },
      { name: "Ekko", file: "ekko.png" },
      { name: "Illaoi", file: "illaoi.png" },
      { name: "Jinx", file: "jinx.png" },
      { name: "Senna", file: "senna.png" },
      { name: "Teemo", file: "teemo.png" },
      { name: "Thresh", file: "thresh.png" },
      { name: "Vi", file: "vi.png" },
      { name: "Warwick", file: "warwick.png" },
      { name: "Yasuo", file: "yasuo.png" },

    ],
  },
};

export const GAME_FOLDER: Record<string, string> = {
  sf6: "SF6",
  ggst: "GGST",
  xko: "2XKO",
};
